### ISSUE TITLE
Decide about Donations

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/governance#25]
@rprouse commented on [Fri Jun 30 2017](https://github.com/nunit/nunit.github.io/issues/6)

The main NUnit site has a donations button and donations page. This was mirrored on the GitHub page. The donations currently go to @CharliePoole to pay for hosting and domains. The @nunit/core-team should decide if we want to continue this and if so where the money should go. This might belong in the governance repo, but I put this here since it needs to be maintained or removed from the website.

I am fine to leave it up for now, but I don't need the money for hosting. If we keep it, I would prefer the money go to stickers for swag for @nunit/core-team members to give out at conferences and user groups.

No rush on this decision, I have update the page to add the recent donors, the donate button still works on the new page and @CharliePoole is still paying for hosting, DNS, etc.

---

@jnm2 commented on [Fri Jun 30 2017](https://github.com/nunit/nunit.github.io/issues/6#issuecomment-312157921)

I think we should continue donations. Some people can't contribute other ways.

Does the decision to join the .NET Foundation have anything to do with this decision?

This just crossed my mind- would anyone be open to the possibility of taking a portion of that and splitting it between team members who are active in the key projects according to a fair and simple rule as a thank you for contributing and an incentive to stay active?

---

@ChrisMaddock commented on [Fri Jun 30 2017](https://github.com/nunit/nunit.github.io/issues/6#issuecomment-312249763)

> I am fine to leave it up for now, but I don't need the money for hosting. If we keep it, I would prefer the money go to stickers for swag for @nunit/core-team members to give out at conferences and user groups.

This sounds sensible to me.

---

@ChrisMaddock commented on [Fri Jul 07 2017](https://github.com/nunit/nunit.github.io/issues/6#issuecomment-313673369)

I'm doing a little organising in the nunit.github.io repo - I'm going to move this to governance - as I think it's first an issue for the Core Team to decide what action to take.

**Comment by jnm2** [comment]
As to where the money should go, @CharliePoole says it's silly to keep sending it to him but what are the options? It would be nice if there was a transparent account it could go in, but I know nothing about such things and I don't want to inflict overhead on us right now.

Seems like the kind of thing the .NET Foundation has guidance on.

**Comment by jnm2** [comment]
Seems like the kind of thing the .NET Foundation has guidance on.

**Comment by CharliePoole** [comment]
@jnm2 The .NET Foundation would take the donations if we were a member and hold them for us in some way. Even starting today, I imagine that it would take a while before that can be in p.lace.

As far as guidance, it seems fairly obvious. Unless / Until we use the .NET Foundation, we need to either stop taking donations or find a place to hold them. For the short term, I don't care much how transparent it is. Setting up a PayPal account is rather trivial.

It seems to me that the key thing is for the core team to decide:

1. Whether we want donations and how they will be used (although the use part could be delayed).

2. Whether we want the request for donations to be as prominent as it is now. That is, if we are emphasizing only three things on the front page, do we think this should be one of them? Maybe we want a latest downloads block instead. I'm not advocating one way or another, just saying it's something we have not discussed.

3. The mechanics of taking and holding the donations. Currently, they go into a business account of mine, because that business was carrying all the expenses in the past.

At one time, NUnit had much higher expenses than it now has. I was paying all of them so I set up the donations button to take care of it. I ran them into the business as revenue and paid the expenses out of the business.

Now we are down to about $35 per year for domain names and hosting is $4 per month rather than $30. It could be that we don't have a need for it any longer, unless there is some desire to collect money for gear of some kind.

**Comment by rprouse** [comment]
I would prefer to see download promoted on the front page and I think any decision we make may change if we join the .NET Foundation.

How about we comment out the buttons for now and then revisit this after we make the decision on the .NET Foundation?

**Comment by CharliePoole** [comment]
That makes sense to me. I think it would be great if each of the latest downloads could be accessed directly from a panel on the front page.

**Comment by OsirisTerje** [comment]
Really makes sense to me too.  
Focus on downloads, makes it real easy for the users.    If space, also point to the documentation wiki.

**Comment by ChrisMaddock** [comment]
Sounds good

**Comment by jnm2** [comment]
Sure.

**Comment by ChrisMaddock** [comment]
AFAIK the Donations page is long gone. 😊
