### ISSUE TITLE
Core Extension Project Leads

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/governance#32]
It would be good to have a clear idea of who's responsible for maintaining the 4 core engine extensions. Three motivations for sorting this out:

1. There's been a number of PRs to the VS project loader recently, and currently no clear plan of how these are going to get into a release.
2. @CharliePoole mentioned the other day he was interested in taking some on - we should facilitate that!
3. These currently seem to fall on @rprouse's plate by default, and that's a very full plate.

I think the first step is to find interested parties. 

Charlie - you've previously mentioned being interested in maintaining several - are you still? If so, which ones are you interested in? Rob - were there any your particularly wished to keep tabs on? I'd be happy to pick some up, although would prefer them not to be the NUnit2 ones, as I know little about it. Anyone else? Traffic is low on these, but I think it would help to have someone with specific responsibility for each.

**Comment by CharliePoole** [comment]
I mentioned to @ChrisMaddock in a kind of aside (I should probably stop doing that) that I had previously volunteered to maintain several projects, at different times. This was a long time ago, or seems like it anyway. Meanwhile, other things have happened. I'm planning on doing some other stuff beyond NUnit. I could have room for a project or two if I knew what they were. IMO, the core team has to say "Help wanted" to lead the following projects... whether they are extensions or something else.

I have always assumed that others in our number would volunteer to lead a project, if only they were asked. It would be interesting to see who is right about that. In the case of the VS project loader, which is where the discussion started, I actually have a candidate I would propose if we wanted it to be run independently.

Without knowing that, I don't want to stick anybody else's neck out for them. 😈 

I have to disagree with one point of @ChrisMaddock 's... If you go by the governance document, there is no default. The organization chair, by design, has no specific role in any project. But if you mean "Rob ends up doing it" then I agree.

**Comment by rprouse** [comment]
I would love to see someone take responsibility for the extensions if we can find someone. I don't use any of them, so I don't have much motivation to keep them up to date. @charliepoole, if you have someone in mind, do you want to gauge their interest privately?

**Comment by ChrisMaddock** [comment]
> IMO, the core team has to say "Help wanted" to lead the following projects...

That's what I was aiming to go with this post! 😄 

>The organization chair, by design, has no specific role in any project. But if you mean "Rob ends up doing it" then I agree.

Agreed!

**Comment by CharliePoole** [comment]
@rprouse I need to follow up on this. Our last communication was back on my birthday, which lasted about four days, so I lost track. 😸 

I'd like to tell the guy I'm thinking of what he would do and what criteria or guidelines he would need to follow if it's an NUnit Project project. To be clear, I understand and I'll make him understand that any guidance will be done in a friendly, collaborative way.

But I think it's fair for him to know in advance what sorts of things require discussion and which are up to his decision, so long as the project is moving along, bugs getting fixed, etc. That would include but not be limited to things like documentation (where, how), review process, releasing, etc. Anything I missed?

**Comment by ChrisMaddock** [comment]
Governance.md seemed a pretty good summary when I was looking round things for NUnit.StaticAssert. (Which is another issue I promise I'm coming back to...busy few weeks!)

**Comment by CharliePoole** [comment]
@ChrisMaddock Good thought. I used a snippet from that to explain the job to my guy. If he agrees I'll propose him to the team via email. I think we have agreed that talking about potential candidates for joining a team or (especially) leading one should be private.

**Comment by CharliePoole** [comment]
I corresponded with @ManfredLange about the possible role of project lead for the VS project loader. He feels he can't really do it because of heavy job responsibilities at this time, but is willing to contribute when the issues align with his clients needs. I went ahead and invited him to be a collaborator on the project, since we don't have specific teams for each extension.

Manfred has already contributed to the project in areas where I couldn't and is well-known to me as the author of csunit, which he created at or shortly after the time when NUnit was first created. He is also a contributor on the gui project.

**Comment by rprouse** [comment]
Welcome @ManfredLange. I didn't realize you did csUnit. It was the first unit test framework I used and I still have old code using it 👍

**Comment by ChrisMaddock** [comment]
Great to have @ManfredLange on board, to help out with the VS extension. 😄 

I think the conclusion of this issue, is that we have no obvious/willing candidates for these roles - they remain something that can be filled if the right person comes along, otherwise the engine team will keep taking responsibility.

I'll make a separate issue for the VS extension I was concerned about, and close this one down.
