### ISSUE TITLE
Update Code of Conduct on all active projects

### ISSUE THREAD

**Issue by rprouse** [nunit/governance#41]
The .NET Foundation now has a standard [code of conduct](https://dotnetfoundation.org/about/code-of-conduct) for all projects and the [markdown file](https://github.com/dotnet-foundation/website/blob/main/CODE_OF_CONDUCT.md) linking to it.

This standardizes the CoC across member projects but more importantly for us it provides an email address for reports and a committee for investigations.

We need to update the CoC for each of our active projects.

- [x] NUnit
- [x] NUnit Console/Engine
- [x] NUnit 3 Adapter
- [x] Governance
- [x] Website
- [x] Docs
- [x] nunit.analyzers
- [x] dotnet-new-nunit

**Comment by rprouse** [comment]
Pull requests submitted for all repos.

**Comment by mikkelbu** [comment]
I should have looked into this in more detail before rather than now. But reading the code of conduct I have two questions. Who are the "Community leaders" and what if we don't agree with them? I'm especially thinking of 

> Community leaders have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, and will communicate reasons for moderation decisions when appropriate.

Will we be notified if a user create an issue, PR, ... that they remove or edit or how is the intended flow? I know that this probably happens very rarely, but it would be nice to know about the details before it happens.

**Comment by rprouse** [comment]
@mikkelbu the community leaders are volunteers from several member projects that review any submissions. We keep their names secret to protect them from reprisal.

So far, most issues are dealt with by the member projects themselves. The committee is only there as an impartial third party if it cannot be resolved. Anything that the committee decides is also reviewed by the board to ensure fairness. I would assume that the committee would also work with the project maintainers to resolve the issue.
